language: go

sudo: required
dist: trusty

go:
  - 1.10.x
  - master
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: master
    - go: tip

cache: apt

install:
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - make test

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
